# Generated by Django 4.2.20 on 2025-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_fix_soft_deleted_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresource',
            name='id_type',
            field=models.CharField(choices=[('wikidata', 'WikiData'), ('isbn10', 'ISBN10'), ('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('cubn', 'CUBN'), ('isrc', 'ISRC'), ('gtin', 'GTIN UPC EAN'), ('rss', 'RSS Feed URL'), ('imdb', 'IMDb'), ('tmdb_tv', 'TMDB TV Serie'), ('tmdb_tvseason', 'TMDB TV Season'), ('tmdb_tvepisode', 'TMDB TV Episode'), ('tmdb_movie', 'TMDB Movie'), ('goodreads', 'Goodreads'), ('goodreads_work', 'Goodreads Work'), ('googlebooks', 'Google Books'), ('doubanbook', 'Douban Book'), ('doubanbook_work', 'Douban Book Work'), ('doubanmovie', 'Douban Movie'), ('doubanmusic', 'Douban Music'), ('doubangame', 'Douban Game'), ('doubandrama', 'Douban Drama'), ('doubandrama_version', 'Douban Drama Version'), ('bookstw', 'BooksTW Book'), ('bibliotekdk_edition', 'Bibliotek.dk'), ('bibliotekdk_ereolen', 'eReolen.dk'), ('bibliotekdk_work', 'Bibliotek.dk'), ('bandcamp', 'Bandcamp'), ('spotify_album', 'Spotify Album'), ('spotify_show', 'Spotify Podcast'), ('discogs_release', 'Discogs Release'), ('discogs_master', 'Discogs Master'), ('musicbrainz', 'MusicBrainz ID'), ('igdb', 'IGDB Game'), ('bgg', 'BGG Boardgame'), ('steam', 'Steam Game'), ('bangumi', 'Bangumi'), ('apple_podcast', 'Apple Podcast'), ('apple_music', 'Apple Music'), ('fedi', 'Fediverse'), ('qidian', 'Qidian'), ('ypshuo', 'Ypshuo'), ('ao3', 'Archive of Our Own'), ('jjwxc', 'JinJiang')], max_length=50, verbose_name='IdType of the source site'),
        ),
        migrations.AlterField(
            model_name='itemlookupid',
            name='id_type',
            field=models.CharField(blank=True, choices=[('wikidata', 'WikiData'), ('isbn10', 'ISBN10'), ('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('cubn', 'CUBN'), ('isrc', 'ISRC'), ('gtin', 'GTIN UPC EAN'), ('rss', 'RSS Feed URL'), ('imdb', 'IMDb'), ('tmdb_tv', 'TMDB TV Serie'), ('tmdb_tvseason', 'TMDB TV Season'), ('tmdb_tvepisode', 'TMDB TV Episode'), ('tmdb_movie', 'TMDB Movie'), ('goodreads', 'Goodreads'), ('goodreads_work', 'Goodreads Work'), ('googlebooks', 'Google Books'), ('doubanbook', 'Douban Book'), ('doubanbook_work', 'Douban Book Work'), ('doubanmovie', 'Douban Movie'), ('doubanmusic', 'Douban Music'), ('doubangame', 'Douban Game'), ('doubandrama', 'Douban Drama'), ('doubandrama_version', 'Douban Drama Version'), ('bookstw', 'BooksTW Book'), ('bibliotekdk_edition', 'Bibliotek.dk'), ('bibliotekdk_ereolen', 'eReolen.dk'), ('bibliotekdk_work', 'Bibliotek.dk'), ('bandcamp', 'Bandcamp'), ('spotify_album', 'Spotify Album'), ('spotify_show', 'Spotify Podcast'), ('discogs_release', 'Discogs Release'), ('discogs_master', 'Discogs Master'), ('musicbrainz', 'MusicBrainz ID'), ('igdb', 'IGDB Game'), ('bgg', 'BGG Boardgame'), ('steam', 'Steam Game'), ('bangumi', 'Bangumi'), ('apple_podcast', 'Apple Podcast'), ('apple_music', 'Apple Music'), ('fedi', 'Fediverse'), ('qidian', 'Qidian'), ('ypshuo', 'Ypshuo'), ('ao3', 'Archive of Our Own'), ('jjwxc', 'JinJiang')], max_length=50, verbose_name='source site'),
        ),
    ]
